### ISSUE TITLE
将每日的Bing美图缓存至本地

### ISSUE THREAD

**Issue by MintTang** [jinzhijie/PyBingApi#1]
希望能自动缓存每日的bing美图至本地并在访问时自动显示本地链接

**Comment by SerinaNya** [comment]
会的会的

**Comment by MintTang** [comment]
谢谢dalao

**Comment by SerinaNya** [comment]
用 crontab 定时执行 `$ python3 cacheimg.py` 即可
[v0.1-beta.1](https://github.com/jinzhijie/PyBingApi/releases/tag/v0.1-beta.1)
